// <auto-generated />
using System;
using MayFly.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MayFly.Api.Migrations
{
    [DbContext(typeof(MayFlyContext))]
    [Migration("20260701195346_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MayFly.Api.Domain.Instance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CapabilityToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContainerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatorIp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DbName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DbPasswordEnc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DbUser")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Engine")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InitialData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InternalHost")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("LastSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("PublicPort")
                        .HasColumnType("integer");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StorageQuotaMb")
                        .HasColumnType("integer");

                    b.Property<int>("TtlHours")
                        .HasColumnType("integer");

                    b.Property<string>("VolumeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CapabilityToken")
                        .IsUnique();

                    b.HasIndex("SessionId");

                    b.HasIndex("CreatorIp", "State");

                    b.ToTable("Instances");
                });

            modelBuilder.Entity("MayFly.Api.Domain.QueryLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InstanceId")
                        .HasColumnType("uuid");

                    b.Property<int>("RowCount")
                        .HasColumnType("integer");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("InstanceId");

                    b.ToTable("QueryLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
